"""Add Blockchain Model

Revision ID: 89efdacd9494
Revises: ecb9d61e523b
Create Date: 2025-02-16 18:02:26.100928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89efdacd9494'
down_revision = 'ecb9d61e523b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('data', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain')
    # ### end Alembic commands ###
